// generated by Fast Light User Interface Designer (fluid) version 1.0302
#include "JanelaProdutos.h"
#include "Core.h"				// time() sqlite functions and more

Fl_Double_Window* JanelaExcluirProdutos; //Widget da Janela

// Widgets na janela
Fl_Input *nome_produto_excluir,
		 *valor_produto_excluir,
		 *quantidade_produto_excluir,
		 *categoria_produto_excluir,
		 *descricao_produto_excluir;
Fl_Button *cancelar_produto_excluir,
		  *excluir_produto_excluir;

int PK_EXLUIR_PRODUTO;

void excluir_cancelar_window_callback (Fl_Widget*, void*)
{
	JanelaExcluirProdutos->hide();
}
void excluir_window_callback (Fl_Widget*, void*)
{
	//Rotina DELETE
	int hotspot = fl_message_hotspot();
	fl_message_hotspot(0);
	fl_message_title("Aviso");
	int rep = fl_choice("Deseja mesmo excluir?", 
		"Nao", "Sim", "Não sei...");
	fl_message_hotspot(hotspot);
	if (rep==1)
	{
		JanelaExcluirProdutos->hide();
		Produto prod_selecionado(PK_EXLUIR_PRODUTO);
		if(prod_selecionado.sql_delete_produto()) {
			fl_alert("Produto excluido");
			desenha_tabela_produtos();
		}
	}
}
void DesenhaJanelaDetalhesProdutoExcluir(int PK)
{
	char _buffer[16];// auxiliar onverter tipos float e char

	Produto prod_selecionado(PK);
	PK_EXLUIR_PRODUTO = PK;

	// Inicializa a interface gráfica
	char titulo_consulta[50] = { "Titulo Default" };
	sprintf (titulo_consulta, "Consulta Produto %s - G3Software", prod_selecionado.getNome());
	JanelaExcluirProdutos = new Fl_Double_Window(670, 300, titulo_consulta);

	nome_produto_excluir = new Fl_Input(105, 110, 340, 25, "Nome:");
	nome_produto_excluir->tooltip("Nome do produto.");
	nome_produto_excluir->insert(prod_selecionado.getNome(),strlen(prod_selecionado.getNome()));
	nome_produto_excluir->deactivate();


	valor_produto_excluir = new Fl_Input(535, 110, 115, 25, "Valor (R$):");
	valor_produto_excluir->tooltip("Valor do produto.");
	sprintf (_buffer, "%.2f", prod_selecionado.getValor());
	valor_produto_excluir->insert(_buffer,strlen(_buffer));
	valor_produto_excluir->deactivate();

	categoria_produto_excluir = new Fl_Input(105, 140, 340, 25, "Categoria:");
	categoria_produto_excluir->tooltip("Categoria do Produto");
	categoria_produto_excluir->insert(prod_selecionado.getCategoria(),strlen(prod_selecionado.getCategoria()));
	categoria_produto_excluir->deactivate();


	quantidade_produto_excluir = new Fl_Input(535, 140, 115, 25, "Quantidade:");
	quantidade_produto_excluir->tooltip("Quantidade de unidades do produto.");
	sprintf (_buffer, "%d", prod_selecionado.getQuantidade());
	quantidade_produto_excluir->insert(_buffer,strlen(_buffer));
	quantidade_produto_excluir->deactivate();

	descricao_produto_excluir = new Fl_Input(105, 170, 545, 65, "Descri\303\247\303\243o:");
	descricao_produto_excluir->tooltip("Descricao do Produto.");
	descricao_produto_excluir->insert(prod_selecionado.getDescricao(),strlen(prod_selecionado.getDescricao()));
	descricao_produto_excluir->deactivate();	

	excluir_produto_excluir = new Fl_Button(510, 260, 135, 25, "Excluir");
	excluir_produto_excluir->tooltip("Excluir dados.");
	excluir_produto_excluir->shortcut(0xff0d);
	excluir_produto_excluir->align(Fl_Align(256));
	excluir_produto_excluir->image(image_accept);
	excluir_produto_excluir->callback(excluir_window_callback);

	cancelar_produto_excluir = new Fl_Button(375, 260, 135, 25, "Cancelar");
	cancelar_produto_excluir->tooltip("Cancela a exclusao.");
	cancelar_produto_excluir->align(Fl_Align(256));
	cancelar_produto_excluir->image(image_decline);
	cancelar_produto_excluir->callback(excluir_cancelar_window_callback);


	Fl_Group* bg_logo = new Fl_Group(0, 0, 670, 100);
	bg_logo->image(image_default_bg); // default in code image

	bg_logo->align(Fl_Align(FL_ALIGN_CENTER));
	bg_logo->end();

	JanelaExcluirProdutos->show();
	JanelaExcluirProdutos->end();
}