// generated by Fast Light User Interface Designer (fluid) version 1.0302
#include "JanelaClientes.h"
#include "Core.h"				// time() sqlite functions and more


Fl_Double_Window* JanelaEditarClientes; //Widget da Janela

// Widgets na janela
Fl_Input *nome_editar,
		 *CEP_editar,
		 *numero_editar,
		 *complemento_editar,
		 *bairro_editar,
		 *Fone_editar,
		 *cnpjcpf_editar,
		 *email_editar,
		 *observ_editar,
		 *rua_editar,
		 *cidade_editar;
Fl_Input_Choice *Pessoa_editar, *estado_editar;
Fl_Button *gravar_edicao,*cancelar_edicao, *confirmar_visualizacao_cliente, *editar_cliente, *cancelar_edicao_cliente, *gravar_cliente_editado;

int PK_EDITAR_CLIENTES; //<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< PK NESTA JANELA

//-------------------------- Callbacks da janela  ------------------------------------------------
void cb_fechar_janelaEditarClientes(Fl_Widget*, void*)
{
	JanelaEditarClientes->hide();
	delete JanelaEditarClientes;
	JanelaEditarClientes = 0;
}
void cb_habilitar_edicao_cliente(Fl_Widget*, void*)
{
	nome_editar->activate();
	CEP_editar->activate();
	numero_editar->activate();
	complemento_editar->activate();
	bairro_editar->activate();
	Fone_editar->activate();
	cnpjcpf_editar->activate();
	email_editar->activate();
	observ_editar->activate();
	rua_editar->activate();
	cidade_editar->activate();
	Pessoa_editar->activate();
	estado_editar->activate();


	//Habilita campos de gravação e cancelamento
	cancelar_edicao_cliente->show();
	gravar_cliente_editado->show();

	editar_cliente->deactivate();
	confirmar_visualizacao_cliente->deactivate();
}
void cb_desabilitar_edicao_cliente(Fl_Widget*, void*)
{
	nome_editar->deactivate();
	CEP_editar->deactivate();
	numero_editar->deactivate();
	complemento_editar->deactivate();
	bairro_editar->deactivate();
	Fone_editar->deactivate();
	cnpjcpf_editar->deactivate();
	email_editar->deactivate();
	observ_editar->deactivate();
	rua_editar->deactivate();
	cidade_editar->deactivate();
	Pessoa_editar->deactivate();
	estado_editar->deactivate();

	//Habilita campos de gravação e cancelamento
	cancelar_edicao_cliente->hide();
	gravar_cliente_editado->hide();

	editar_cliente->activate();
	confirmar_visualizacao_cliente->activate();
}
void cb_atualizar_cliente_editado(Fl_Widget*, void*)
{
	//Rotina UPDATE
	int resultset_command; // 1 se foir executado, 0 se não foi executado
	Cliente cliente_alterado(PK_EDITAR_CLIENTES,
							 (char*)nome_editar->value(),
							 (char*)Pessoa_editar->value(),
							 (char*)cnpjcpf_editar->value(),
							 (char*)CEP_editar->value(),
							 (char*)cidade_editar->value(),
							 (char*)bairro_editar->value(),
							 (char*)rua_editar->value(),
							 atoi(numero_editar->value()),
							 (char*)estado_editar->value(),
							 (char*)complemento_editar->value(),
							 (char*)Fone_editar->value(),
							 (char*)email_editar->value(),
							 (char*)observ_editar->value());
	
	resultset_command = cliente_alterado.sql_update_cliente();
	if(resultset_command)
	{

		desenha_tabela_clientes(); // atualiza a janela

		cancelar_edicao_cliente->hide();
		gravar_cliente_editado->hide();
		editar_cliente->activate();
		confirmar_visualizacao_cliente->activate();
	}
}
void cb_cancelar_edicao_cliente(Fl_Widget*, void*)
{

	// Visualizar
	confirmar_visualizacao_cliente->activate();
	editar_cliente->activate();
	cancelar_edicao_cliente->hide();
	gravar_cliente_editado->hide();
}
//-------------------------- Callbacks da janela  ------------------------------------------------



void DesenhaJanelaDetalhesCliente(int PK)
{
	char auxiliar[32]; // auxiliar para conversão de numeros para char
	PK_EDITAR_CLIENTES = PK;
	Cliente cliente_selecionado(PK_EDITAR_CLIENTES);

	// Inicializa a interface gráfica
	JanelaEditarClientes = new Fl_Double_Window(670, 545, "Cadastro de Clientes - G3Software");
	//JanelaEditarClientes->callback(cb_fechar_JanelaEditarClientes);

	cnpjcpf_editar = new Fl_Input(105, 110, 225, 25, "CNPJ/CPF:");
	cnpjcpf_editar->tooltip("Nome do cliente.");
	cnpjcpf_editar->color((Fl_Color)231);

	Pessoa_editar = new Fl_Input_Choice(535, 110, 115, 25, "Pessoa:");
	Pessoa_editar->add("fisica");
	Pessoa_editar->add("juridica");
	
	nome_editar = new Fl_Input(105, 145, 550, 25, "Nome:");
	nome_editar->tooltip("Nome do cliente.");
	nome_editar->color((Fl_Color)231);
	nome_editar->image(image_people);
	
	CEP_editar = new Fl_Input(105, 210, 160, 25, "CEP:");
	CEP_editar->tooltip("Nome do cliente.");
	CEP_editar->color((Fl_Color)231);

	cidade_editar = new Fl_Input(320, 210, 330, 25, "Cidade:");
	cidade_editar->tooltip("Cidade do cliente.");

	bairro_editar = new Fl_Input(105, 240, 325, 25, "Bairro:");
	bairro_editar->tooltip("Bairro do cliente.");
	
	estado_editar = new Fl_Input_Choice(490, 240, 160, 25, "Estado:");
	estado_editar->add("AC");
	estado_editar->add("AL");
	estado_editar->add("AP");
	estado_editar->add("AM");
	estado_editar->add("BA");
	estado_editar->add("CE");
	estado_editar->add("DF");
	estado_editar->add("ES");
	estado_editar->add("GO");
	estado_editar->add("MA");
	estado_editar->add("MT");
	estado_editar->add("MS");
	estado_editar->add("MG");
	estado_editar->add("PA");
	estado_editar->add("PB");
	estado_editar->add("PR");
	estado_editar->add("PE");
	estado_editar->add("PI");
	estado_editar->add("RJ");
	estado_editar->add("RN");
	estado_editar->add("RS");
	estado_editar->add("RR");
	estado_editar->add("SC");
	estado_editar->add("SP");
	estado_editar->add("SE");
	estado_editar->add("TO");

	estado_editar->tooltip("Estado onde reside o cliente.");

	rua_editar = new Fl_Input(105, 270, 325, 25, "Rua:");
	rua_editar->tooltip("Rua onde reside o cliente.");

	numero_editar = new Fl_Input(490, 270, 160, 25, "N\303\272mero:");
	numero_editar->tooltip("N\303\272mero da rua onde reside o cliente.");
    
	complemento_editar = new Fl_Input(105, 300, 545, 25, "Complemento:");
	complemento_editar->tooltip("Complemento da residencia do cliente.");
	
	Fone_editar = new Fl_Input(105, 355, 225, 25, "Fone:");
	Fone_editar->tooltip("Nome do cliente.");
    
	email_editar = new Fl_Input(105, 385, 545, 25, "E-mail:");
	email_editar->tooltip("Nome do cliente.");

	observ_editar = new Fl_Input(105, 425, 545, 65, "Observa\303\247\303\243o:");
	observ_editar->tooltip("Nome do cliente.");



	// Visualizar

	confirmar_visualizacao_cliente = new Fl_Button(510, 505, 135, 25, "OK");
	confirmar_visualizacao_cliente->tooltip("fecha a janela");
	confirmar_visualizacao_cliente->shortcut(0xff0d);
	confirmar_visualizacao_cliente->align(Fl_Align(256));
	confirmar_visualizacao_cliente->image(image_accept);
	confirmar_visualizacao_cliente->callback(cb_fechar_janelaEditarClientes);

	editar_cliente = new Fl_Button(375, 505, 135, 25, "Editar");
	editar_cliente->tooltip("Editar informacoes do produto.");
	editar_cliente->align(Fl_Align(256));
	editar_cliente->image(image_edit);
	editar_cliente->callback(cb_habilitar_edicao_cliente);



	// Editar

	cancelar_edicao_cliente = new Fl_Button(105, 505, 135, 25, "Cancelar Edicao");
	cancelar_edicao_cliente->tooltip("Grava novas informacoes do produto.");
	cancelar_edicao_cliente->align(Fl_Align(256));
	cancelar_edicao_cliente->image(image_decline);
	cancelar_edicao_cliente->hide();
	cancelar_edicao_cliente->callback(cb_desabilitar_edicao_cliente);

	gravar_cliente_editado = new Fl_Button(240, 505, 135, 25, "Gravar Edicao");
	gravar_cliente_editado->tooltip("Grava novas informacoes do produto.");
	gravar_cliente_editado->align(Fl_Align(256));
	gravar_cliente_editado->image(image_save);
	gravar_cliente_editado->hide();
	gravar_cliente_editado->callback(cb_atualizar_cliente_editado);



	cb_desabilitar_edicao_cliente(0,0);


	Fl_Group* bg_logo = new Fl_Group(0, 0, 670, 100);
	bg_logo->image(image_default_bg); // default in code image

	bg_logo->align(Fl_Align(FL_ALIGN_CENTER));
	bg_logo->end();


	nome_editar->value(cliente_selecionado.getnome());
	CEP_editar->value(cliente_selecionado.getcep());
	sprintf(auxiliar,"%d", cliente_selecionado.getnumero());
	numero_editar->value(auxiliar);
	complemento_editar->value(cliente_selecionado.getcomplemento());
	bairro_editar->value(cliente_selecionado.getbairro());
	Fone_editar->value(cliente_selecionado.getfone());
	cnpjcpf_editar->value(cliente_selecionado.getcpfcnpj());
	email_editar->value(cliente_selecionado.getemail());
	observ_editar->value(cliente_selecionado.getobservacao());
	rua_editar->value(cliente_selecionado.getrua());
	cidade_editar->value(cliente_selecionado.getcidade());
	Pessoa_editar->value(cliente_selecionado.getpessoa());
	estado_editar->value(cliente_selecionado.getestado());

	JanelaEditarClientes->show();
	JanelaEditarClientes->end();
}
