// generated by Fast Light User Interface Designer (fluid) version 1.0302
#include "JanelaProdutos.h"
#include "Core.h"				// time() sqlite functions and more

Fl_Double_Window* JanelaEditarProdutos; //Widget da Janela

// Widgets na janela
Fl_Input *nome_produto_consultar, *valor_produto_consultar,
		 *quantidade_produto_consultar,
		 *categoria_produto_consultar,
		 *descricao_produto_consultar;

Fl_Button *cancelar_produto_consultar,
		  *gravar_produto_consultar,
		  *editar_produto_consultar,
		  *ok_produto_consultar;


int PK_EDITAR_PRODUTOS;

void atribui_valores_anteriores ()
{
	nome_produto_consultar->undo();
	nome_produto_consultar->deactivate();

	valor_produto_consultar->undo();
	valor_produto_consultar->deactivate();

	categoria_produto_consultar->undo();
	categoria_produto_consultar->deactivate();

	quantidade_produto_consultar->undo();
	quantidade_produto_consultar->deactivate();

	descricao_produto_consultar->undo();
	descricao_produto_consultar->deactivate();
}

void consultar_cancelar_window_callback (Fl_Widget*, void*)
{
	int hotspot = fl_message_hotspot();
	fl_message_hotspot(0);
	fl_message_title("Aviso");
	int rep = fl_choice("Deseja mesmo cancelar a edicao?", 
		"Nao", "Sim", "Não sei...");
	fl_message_hotspot(hotspot);
	if (rep==1) {
		cancelar_produto_consultar->hide();
		gravar_produto_consultar->hide();
		atribui_valores_anteriores();
		ok_produto_consultar->activate();
		editar_produto_consultar->activate();
	}
	else if (rep==2)
		fl_message("Bom, talvez voce devesse saber antes de cancelar...");
}

void consultar_gravar_window_callback (Fl_Widget*, void*)
{
	//Rotina UPDATE
	int resultset_command; // 1 se foir executado, 0 se não foi executado
	Produto produto_alterado(PK_EDITAR_PRODUTOS, (char*) nome_produto_consultar->value(), atof(valor_produto_consultar->value()), atoi(quantidade_produto_consultar->value()),
							    (char*) categoria_produto_consultar->value(), (char*) descricao_produto_consultar->value());
	
	resultset_command = produto_alterado.sql_update_produto();
	if(resultset_command) {
		cancelar_produto_consultar->hide();
		gravar_produto_consultar->hide();
		ok_produto_consultar->activate();
		editar_produto_consultar->activate();
		desenha_tabela_produtos();
	}
}

void consultar_ok_window_callback (Fl_Widget*, void*)
{
	JanelaEditarProdutos->hide();
}

void consultar_editar_window_callback (Fl_Widget*, void*)
{
	//Habilita campos para edição
	nome_produto_consultar->activate();
	valor_produto_consultar->activate();
	categoria_produto_consultar->activate();
	quantidade_produto_consultar->activate();
	descricao_produto_consultar->activate();
	editar_produto_consultar->deactivate();

	//Desabilita a finalização da Visualização
	ok_produto_consultar->deactivate();

	//Habilita campos de gravação e cancelamento
	cancelar_produto_consultar->show();
	gravar_produto_consultar->show();
}

void DesenhaJanelaDetalhesProduto(int PK)
{
	char buffer[10] = { "Teste" }; //Buffer para conversão de dados
	Produto prod_selecionado(PK);
	PK_EDITAR_PRODUTOS = PK;

	// Inicializa a interface gráfica
	char titulo_consulta[50] = { "Titulo Default" };
	sprintf (titulo_consulta, "Consulta Produto %s - G3Software", prod_selecionado.getNome());
	JanelaEditarProdutos = new Fl_Double_Window(670, 300, titulo_consulta);

	nome_produto_consultar = new Fl_Input(105, 110, 340, 25, "Nome:");
	nome_produto_consultar->tooltip("Nome do produto.");
	nome_produto_consultar->insert(prod_selecionado.getNome(),strlen(prod_selecionado.getNome()));
	nome_produto_consultar->deactivate();


	valor_produto_consultar = new Fl_Input(535, 110, 115, 25, "Valor (R$):");
	valor_produto_consultar->tooltip("Valor do produto.");
	sprintf (buffer, "%.2f", prod_selecionado.getValor());
	valor_produto_consultar->insert(buffer,strlen(buffer));
	valor_produto_consultar->deactivate();

	categoria_produto_consultar = new Fl_Input(105, 140, 340, 25, "Categoria:");
	categoria_produto_consultar->tooltip("Categoria do Produto");
	categoria_produto_consultar->insert(prod_selecionado.getCategoria(),strlen(prod_selecionado.getCategoria()));
	categoria_produto_consultar->deactivate();


	quantidade_produto_consultar = new Fl_Input(535, 140, 115, 25, "Quantidade:");
	quantidade_produto_consultar->tooltip("Quantidade de unidades do produto.");
	sprintf (buffer, "%d", prod_selecionado.getQuantidade());
	quantidade_produto_consultar->insert(buffer,strlen(buffer));
	quantidade_produto_consultar->deactivate();

	descricao_produto_consultar = new Fl_Input(105, 170, 545, 65, "Descri\303\247\303\243o:");
	descricao_produto_consultar->tooltip("Descricao do Produto.");
	descricao_produto_consultar->insert(prod_selecionado.getDescricao(),strlen(prod_selecionado.getDescricao()));
	descricao_produto_consultar->deactivate();

	ok_produto_consultar = new Fl_Button(510, 260, 135, 25, "OK");
	ok_produto_consultar->tooltip("Finalizar consulta");
	ok_produto_consultar->shortcut(0xff0d);
	ok_produto_consultar->align(Fl_Align(256));
	ok_produto_consultar->image(image_accept);
	ok_produto_consultar->callback(consultar_ok_window_callback);

	editar_produto_consultar = new Fl_Button(375, 260, 135, 25, "Editar");
	editar_produto_consultar->tooltip("Editar informacoes do produto.");
	editar_produto_consultar->align(Fl_Align(256));
	editar_produto_consultar->image(image_edit);
	editar_produto_consultar->callback(consultar_editar_window_callback);

	gravar_produto_consultar = new Fl_Button(240, 260, 135, 25, "Gravar Edicao");
	gravar_produto_consultar->tooltip("Grava novas informacoes do produto.");
	gravar_produto_consultar->align(Fl_Align(256));
	gravar_produto_consultar->image(image_save);
	gravar_produto_consultar->hide();
	gravar_produto_consultar->callback(consultar_gravar_window_callback);

	cancelar_produto_consultar = new Fl_Button(105, 260, 135, 25, "Cancelar Edicao");
	cancelar_produto_consultar->tooltip("Grava novas informacoes do produto.");
	cancelar_produto_consultar->align(Fl_Align(256));
	cancelar_produto_consultar->image(image_decline);
	cancelar_produto_consultar->hide();
	cancelar_produto_consultar->callback(consultar_cancelar_window_callback);


	Fl_Group* bg_logo = new Fl_Group(0, 0, 670, 100);
	bg_logo->image(image_default_bg); // default in code image

	bg_logo->align(Fl_Align(FL_ALIGN_CENTER));
	bg_logo->end();

	JanelaEditarProdutos->show();
	JanelaEditarProdutos->end();
}